[build]
  publish = "."

[context.production]
  environment = { OPENAI_API = "", MAILJET_API_KEY = "", MAILJET_SECRET_KEY = "", DATABASE_URL = "" }

[context.development]
  environment = { OPENAI_API = "", MAILJET_API_KEY = "", MAILJET_SECRET_KEY = "", DATABASE_URL = "" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 