[build]
  publish = "."

[context.production]
  environment = { OPENAI_API = "", MAILJET_API_KEY = "", MAILJET_SECRET_KEY = "" }

[context.development]
  environment = { OPENAI_API = "", MAILJET_API_KEY = "", MAILJET_SECRET_KEY = "" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Stripe webhook needs raw body for signature verification
[[functions]]
  path = "/.netlify/functions/stripe-webhook"
  [functions.settings]
    type = "synchronous"
    raw_body = true 